[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
changelist-data = "^0.2"

[tool.poetry.group.test.dependencies]
optional = true
pytest = "8.3.4"
pytest-cov = "5.0.0"

[tool.poetry.group.docs.dependencies]
optional = true
mkdocs = "*"
